import os
import logging

from oci.auth.signers import get_resource_principals_signer

# Logging variables
ENV_LOG_LEVEL = 'LOG_LEVEL'

# Cache variables
ENV_CACHE = 'OCI_CACHE'
ENV_CACHE_PORT = 'CACHE_PORT'
ENV_CACHE_DB = 'CACHE_DB'
ENV_CACHE_EXPIRY = 'CACHE_EXPIRE'

# Authentication variables
ENV_SECRET = 'APP_SECRET'
ENV_IDM = 'IDM_URL'
ENV_KEYPASS = 'KEY_PASS'

# Tags variables
ENV_TNS = 'TAG_NAMESPACE'
ENV_TKEY = 'TAG_KEY'
ENV_FNS = 'FILTER_NAMESPACE'
ENV_FKEY = 'FILTER_KEY'

class Environment:
    
    def __init__(self):
        # Logging variables
        self.log_level = os.getenv(ENV_LOG_LEVEL, logging.INFO)
        self.log_handler = None

        # Cache variables
        self.cache = os.getenv(ENV_CACHE)
        cache_port = os.getenv(ENV_CACHE_PORT, '6379')
        self.cache_port = int(cache_port) # Needs to be an int
        cache_db = os.getenv(ENV_CACHE_DB, '2')
        self.cache_db = int(cache_db) # Needs to be an int
        expiry = os.getenv(ENV_CACHE_EXPIRY, '3600')
        self.cache_expiry = int(expiry) # Needs to be an int

        # Tag variables
        self.tag_namespace = os.getenv(ENV_TNS) # Namespace to ID ownership
        self.tag_key = os.getenv(ENV_TKEY) # Tag key should be owner ID

        # Set filter namespace if present else use tag namespace
        self.filter_namespace = (os.getenv(ENV_FNS) if os.getenv(ENV_FNS)
            else self.tag_namespace)
        self.filter_key = os.getenv(ENV_FKEY)

        # IDM endpoint
        self.idm_url = os.getenv(ENV_IDM)

        # Password to assign to private keys generated by cryptography
        self.key_passwd = os.getenv(ENV_KEYPASS)

        # OCI Vault secret with format "Client_ID:Client_Secret"
        self.secret = os.getenv(ENV_SECRET)

        # OCI signer to be used for elevated privilege tasks
        self.signer = get_resource_principals_signer()
        
        # Get region from signer
        self.region = self.signer.region
        self.tenancy_id = self.signer.tenancy_id

    def __str__(self):
        return f'{self.__class__}:{self.__dict__}'

    # Set loggers using factory for standardization
    def log_factory(self, name: str, **kwargs) -> logging.Logger:
        logger = logging.getLogger(name)
        logger.handlers.clear()
        
        # StreamHandler as default
        if not self.log_handler: log_handler = logging.StreamHandler()

        logger.addHandler(log_handler)
        logger.setLevel(self.log_level)

        return logger
