title: "OKE Terraform Stack"
description: "Schema for OCI Resource Manager variables used to provision OKE."
schemaVersion: 1.1.0

locale: "en"

variableGroups:
  - title: "OCI Authentication"
    variables:
      - tenancy_ocid
      - user_ocid
      - fingerprint
      - private_key
      - region
    visible: false

  - title: "OKE Cluster Configuration"
    variables:
      - compartment_ocid
      - k8s_version
      - custom_nodes

  - title: "Worker Node Configuration"
    variables:
    - node_shape
    - node_ocpus
    - node_memory
    - node_image_ocid
    - worker_ssh_public_key

variables:
  # Authentication
  tenancy_ocid:
    type: string
    title: "Tenancy OCID"
    description: "OCID of the tenancy."
    required: true

  user_ocid:
    type: string
    title: "User OCID"
    description: "OCID of the user for API signing."
    required: true

  fingerprint:
    type: string
    title: "API Key Fingerprint"
    description: "Fingerprint for the uploaded API public key."
    required: true

  private_key:
    type: string
    title: "API Private Key (PEM)"
    description: "Private key in PEM format used for API signing."
    required: true
    sensitive: true

  region:
    type: string
    title: "Region"
    description: "OCI region identifier (e.g., us-ashburn-1)."
    required: true

  # OKE Configuration
  k8s_version:
    type: oci:kubernetes:versions:id
    title: "Kubernetes Version"
    description: "OKE Kubernetes version."
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      clusterOptionId: "all"

  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "Compartment where resources will be created."
    required: true

  custom_nodes:
    type: boolean
    title: "Custom Worker Nodes?"
    default: false
    visible: false # For now

  # Node Configuration
  node_shape:
    type: oci:core:instanceshape:name
    title: "Node Shape"
    description: "Compute shape for worker nodes."
    default: "VM.Standard.A1.Flex"
    required: false
    visible: ${custom_nodes}
    dependsOn:
      compartmentId:  ${compartment_ocid}

  node_ocpus:
    type: number
    title: "Node OCPUs"
    description: "Number of OCPUs for worker nodes (Flex shape)."
    default: 1
    required: false
    minimum: 1
    visible: ${custom_nodes}

  node_memory:
    type: number
    title: "Node Memory (GB)"
    description: "Memory in GB for worker nodes (Flex shape)."
    default: 8
    required: false
    minimum: 1
    visible: ${custom_nodes}

  node_image_ocid:
    title: Node Image    
    description: Worker Image    
    type: oci:core:image:id    
    required: true   
    visible: ${custom_nodes} 
    dependsOn:      
       compartmentId: ${compartment_ocid}
       operatingSystem: "Oracle Linux"
       shape: ${node_shape}

  worker_ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Worker Node SSH Public Key"
    description: "SSH public key injected into worker nodes for SSH access."
    required: true
